[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "RPackageManager"
version = "0.1.0"
description = "A wrapper for rpy2 for managing R packages in Python environments."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "rpy2>=3.5.0",
    "pandas>=1.0.0"
]

[project.urls]
Homepage = "https://github.com/vxtnv/RPackageManager"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages]
find = {}
include = ["RPackageManager"]




